import type { Dealer, GovernmentScheme, Review } from './types'

export const DEALERS: Dealer[] = [
  // Mumbai Dealers
  {
    id: 'd1',
    name: 'Green Energy Solutions',
    type: 'biogas',
    address: 'Shop 12, Andheri West',
    city: 'Mumbai',
    lat: 19.1360,
    lng: 72.8270,
    phone: '+91 98765 43210',
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 'd2',
    name: 'Solar Kitchen India',
    type: 'solar',
    address: 'Bandra Kurla Complex',
    city: 'Mumbai',
    lat: 19.0596,
    lng: 72.8295,
    phone: '+91 98765 43211',
    rating: 4.3,
    reviews: 89,
  },
  {
    id: 'd3',
    name: 'Induction World',
    type: 'induction',
    address: 'Dadar TT Circle',
    city: 'Mumbai',
    lat: 19.0170,
    lng: 72.8473,
    phone: '+91 98765 43212',
    rating: 4.7,
    reviews: 234,
  },
  // Delhi Dealers
  {
    id: 'd4',
    name: 'Biogas Hub Delhi',
    type: 'biogas',
    address: 'Connaught Place',
    city: 'Delhi',
    lat: 28.6315,
    lng: 77.2167,
    phone: '+91 98765 43213',
    rating: 4.4,
    reviews: 156,
  },
  {
    id: 'd5',
    name: 'Delhi Solar Store',
    type: 'solar',
    address: 'Nehru Place',
    city: 'Delhi',
    lat: 28.5494,
    lng: 77.2528,
    phone: '+91 98765 43214',
    rating: 4.2,
    reviews: 102,
  },
  {
    id: 'd6',
    name: 'Smart Kitchen Delhi',
    type: 'induction',
    address: 'Karol Bagh',
    city: 'Delhi',
    lat: 28.6519,
    lng: 77.1905,
    phone: '+91 98765 43215',
    rating: 4.6,
    reviews: 189,
  },
  // Pune Dealers
  {
    id: 'd7',
    name: 'Pune Biogas Center',
    type: 'biogas',
    address: 'FC Road',
    city: 'Pune',
    lat: 18.5282,
    lng: 73.8403,
    phone: '+91 98765 43216',
    rating: 4.3,
    reviews: 87,
  },
  {
    id: 'd8',
    name: 'Solar Solutions Pune',
    type: 'solar',
    address: 'Koregaon Park',
    city: 'Pune',
    lat: 18.5362,
    lng: 73.8927,
    phone: '+91 98765 43217',
    rating: 4.5,
    reviews: 112,
  },
  {
    id: 'd9',
    name: 'Electric Kitchen Pune',
    type: 'induction',
    address: 'MG Road',
    city: 'Pune',
    lat: 18.5196,
    lng: 73.8553,
    phone: '+91 98765 43218',
    rating: 4.4,
    reviews: 145,
  },
  // Chennai Dealers
  {
    id: 'd10',
    name: 'Chennai Green Gas',
    type: 'biogas',
    address: 'T. Nagar',
    city: 'Chennai',
    lat: 13.0382,
    lng: 80.2242,
    phone: '+91 98765 43219',
    rating: 4.6,
    reviews: 134,
  },
  {
    id: 'd11',
    name: 'Sun Cook Chennai',
    type: 'solar',
    address: 'Anna Nagar',
    city: 'Chennai',
    lat: 13.0850,
    lng: 80.2101,
    phone: '+91 98765 43220',
    rating: 4.1,
    reviews: 78,
  },
  {
    id: 'd12',
    name: 'Induction Pro Chennai',
    type: 'induction',
    address: 'Adyar',
    city: 'Chennai',
    lat: 13.0042,
    lng: 80.2565,
    phone: '+91 98765 43221',
    rating: 4.5,
    reviews: 167,
  },
  // Bangalore Dealers
  {
    id: 'd13',
    name: 'Bangalore Biogas Works',
    type: 'biogas',
    address: 'Indiranagar',
    city: 'Bangalore',
    lat: 12.9716,
    lng: 77.6099,
    phone: '+91 98765 43222',
    rating: 4.7,
    reviews: 198,
  },
  {
    id: 'd14',
    name: 'Solar Kitchen Bangalore',
    type: 'solar',
    address: 'Koramangala',
    city: 'Bangalore',
    lat: 12.9352,
    lng: 77.6245,
    phone: '+91 98765 43223',
    rating: 4.4,
    reviews: 145,
  },
  {
    id: 'd15',
    name: 'Electric Home Bangalore',
    type: 'induction',
    address: 'HSR Layout',
    city: 'Bangalore',
    lat: 12.9081,
    lng: 77.6476,
    phone: '+91 98765 43224',
    rating: 4.8,
    reviews: 267,
  },
]

export const GOVERNMENT_SCHEMES: GovernmentScheme[] = [
  {
    id: 'gs1',
    name: 'National Biogas and Manure Management Programme (NBMMP)',
    description: 'Central sector scheme to promote biogas plants for cooking and lighting in rural areas.',
    subsidy: 'Up to ₹10,000 per unit',
    eligibility: 'Rural households with cattle ownership',
    states: ['All India'],
    link: 'https://mnre.gov.in/bio-energy/schemes',
    cookingType: 'biogas',
  },
  {
    id: 'gs2',
    name: 'Solar Cooker Subsidy Scheme',
    description: 'State-level subsidies for purchasing solar cookers.',
    subsidy: '30-50% of cost',
    eligibility: 'All households',
    states: ['Maharashtra', 'Gujarat', 'Rajasthan', 'Karnataka'],
    link: 'https://mnre.gov.in/solar/schemes',
    cookingType: 'solar',
  },
  {
    id: 'gs3',
    name: 'PM Ujjwala Yojana 2.0',
    description: 'Free LPG connection with financial assistance for clean cooking fuel.',
    subsidy: 'Free connection + ₹1,600 refill support',
    eligibility: 'BPL families, SC/ST households',
    states: ['All India'],
    link: 'https://pmuy.gov.in',
    cookingType: 'lpg',
  },
  {
    id: 'gs4',
    name: 'Maharashtra Biogas Development Program',
    description: 'State scheme for promoting biogas in urban and semi-urban areas.',
    subsidy: 'Up to ₹15,000 per plant',
    eligibility: 'Maharashtra residents with space for plant',
    states: ['Maharashtra'],
    link: 'https://mahaurja.com/biogas',
    cookingType: 'biogas',
  },
  {
    id: 'gs5',
    name: 'Karnataka Renewable Energy Development (KREDL)',
    description: 'Subsidies for solar cooking equipment and biogas plants.',
    subsidy: '40% subsidy on solar equipment',
    eligibility: 'Karnataka residents',
    states: ['Karnataka'],
    link: 'https://kredl.karnataka.gov.in',
    cookingType: 'solar',
  },
  {
    id: 'gs6',
    name: 'Tamil Nadu Solar Mission',
    description: 'State initiative promoting solar energy adoption including solar cookers.',
    subsidy: 'Up to ₹2,000 per solar cooker',
    eligibility: 'Tamil Nadu residents',
    states: ['Tamil Nadu'],
    link: 'https://teda.in',
    cookingType: 'solar',
  },
  {
    id: 'gs7',
    name: 'Delhi Clean Energy Incentive',
    description: 'Incentives for adopting clean cooking alternatives in Delhi NCR.',
    subsidy: '20% rebate on clean cooking equipment',
    eligibility: 'Delhi NCR residents',
    states: ['Delhi'],
    link: 'https://delhi.gov.in/energy',
    cookingType: 'induction',
  },
]

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Priya S.',
    city: 'Mumbai',
    cookingMethod: 'biogas',
    rating: 5,
    comment: 'Switched to biogas 6 months ago. My monthly cooking costs dropped by 60%! The initial setup was worth it.',
    date: '2024-01-15',
    householdSize: 4,
    verified: true,
  },
  {
    id: 'r2',
    userName: 'Rahul M.',
    city: 'Delhi',
    cookingMethod: 'induction',
    rating: 4,
    comment: 'Induction cooking is so fast and clean. Electricity bills went up slightly but no more waiting for LPG refills.',
    date: '2024-02-20',
    householdSize: 3,
    verified: true,
  },
  {
    id: 'r3',
    userName: 'Anita K.',
    city: 'Pune',
    cookingMethod: 'solar',
    rating: 4,
    comment: 'Great for dal and rice during sunny days. I use induction as backup for monsoon season.',
    date: '2024-01-28',
    householdSize: 2,
    verified: true,
  },
  {
    id: 'r4',
    userName: 'Suresh P.',
    city: 'Chennai',
    cookingMethod: 'biogas',
    rating: 5,
    comment: 'Perfect for our household of 5. We generate enough gas from kitchen waste. Zero fuel costs!',
    date: '2024-03-05',
    householdSize: 5,
    verified: true,
  },
  {
    id: 'r5',
    userName: 'Meera R.',
    city: 'Bangalore',
    cookingMethod: 'induction',
    rating: 5,
    comment: 'Precision cooking and safety features make it perfect for our modern kitchen. Kids can also help safely.',
    date: '2024-02-12',
    householdSize: 4,
    verified: true,
  },
  {
    id: 'r6',
    userName: 'Arun T.',
    city: 'Mumbai',
    cookingMethod: 'solar',
    rating: 3,
    comment: 'Works well in summer but struggling in monsoon. Good as supplementary option.',
    date: '2024-01-20',
    householdSize: 3,
    verified: false,
  },
  {
    id: 'r7',
    userName: 'Kavita J.',
    city: 'Delhi',
    cookingMethod: 'biogas',
    rating: 4,
    comment: 'Initial smell issues but resolved with proper ventilation. Running smoothly for 8 months now.',
    date: '2024-02-28',
    householdSize: 6,
    verified: true,
  },
  {
    id: 'r8',
    userName: 'Deepak N.',
    city: 'Pune',
    cookingMethod: 'induction',
    rating: 5,
    comment: 'Best investment! Fast cooking, easy cleaning, and no gas cylinder worries.',
    date: '2024-03-10',
    householdSize: 2,
    verified: true,
  },
  {
    id: 'r9',
    userName: 'Lakshmi V.',
    city: 'Chennai',
    cookingMethod: 'solar',
    rating: 4,
    comment: 'Chennai sun makes this perfect. Saved a lot on fuel costs. Highly recommend!',
    date: '2024-01-25',
    householdSize: 4,
    verified: true,
  },
  {
    id: 'r10',
    userName: 'Vikram S.',
    city: 'Bangalore',
    cookingMethod: 'biogas',
    rating: 5,
    comment: 'Eco-friendly and economical. Our society installed 10 units and we share the benefits.',
    date: '2024-02-15',
    householdSize: 5,
    verified: true,
  },
]

export const LPG_MONTHLY_COST = 1200 // Average LPG monthly cost in INR for comparison
